export enum WEB_ROUTES {
  FORM = 'form',
  HISTORY = 'history',
  CHANGE_PASSWORD = '/authentication/change-password',
  VENDOR = '/vendor',
  VENDOR_FORM = '/vendor/form',
  VENDOR_ARCHIVE = '/vendor/archive',
  VENDOR_HISTORY = '/vendor/history',
  GRID = 'grid',
  USER = '/user',
  USER_GRID = '/user/grid',
  SIDEMENU_DASHBOARD = 'dashboard',
  SIDEMENU_VENDOR = 'vendor',
  SIDEMENU_INVOICES = 'invoice',
  SIDEMENU_DOCUMENTS = 'documents',
  SIDEMENU_REPORTS = 'reports',
  SIDEMENU_USER = 'user',
  SIDEMENU_SETTINGS = 'settings',
  COMPANY_INFO_FORM = 'company-info-form',
}
