import { WEB_ROUTES } from 'src/consts/routes';
import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '/dashboard/main',
    title: 'Dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: WEB_ROUTES.VENDOR,
    title: 'Vendor',
    iconType: 'material-icons-two-tone',
    icon: 'local_shipping',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'invoice',
    title: 'Invoices',
    iconType: 'material-icons-two-tone',
    icon: 'receipt',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: WEB_ROUTES.SIDEMENU_DOCUMENTS,
    title: 'Documents',
    iconType: 'material-icons-two-tone',
    icon: 'folder',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: WEB_ROUTES.SIDEMENU_REPORTS,
    title: 'Reports',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: WEB_ROUTES.SIDEMENU_USER,
    title: 'Users',
    iconType: 'material-icons-two-tone',
    icon: 'people',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: WEB_ROUTES.SIDEMENU_SETTINGS,
    title: 'Settings',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
