export const configData = {
  API_URL: 'https://dbtest.rovuk.us:4207/',
  DEFAULT_LOADER_GIF: '../assets/images/rovuk-gif.gif',
  INVOICES_STATUS: [
    { name: 'Pending', key: 'Pending' },
    { name: 'Approved', key: 'Approved' },
    { name: 'Rejected', key: 'Rejected' },
    { name: 'Late', key: 'Late' },
    { name: 'Paid', key: 'Paid' },
    { name: 'Unpaid', key: 'Unpaid' },
    { name: 'Overdue', key: 'Overdue' },
  ],
  SITELANGUAGES: ['es', 'en'],
  INITIALLANGUAGE: 'en',
  LANGUAGE_ARRAY: [
    { name: 'English', value: 'en' },
    { name: 'Español', value: 'es' },
  ],
  PRIME_VENDOR_TYPE: 'Prime',
  gender: [
    { value: 'Male', tmp_lanaguage: 'COMMON.GENDER_ALL.Male_All' },
    { value: 'Female', tmp_lanaguage: 'COMMON.GENDER_ALL.Female_All' },
  ],
  Status: [
    { value: 1, viewValue: 'Active', tmp_lanaguage: 'COMMON.STATUS.ACTIVE' },
    {
      value: 2,
      viewValue: 'Inactive',
      tmp_lanaguage: 'COMMON.STATUS.INACTIVE',
    },
  ],
  MAILBOX_MONITOR_TIME: [
    { time: '5 minutes', value: 'Every 5 min', cron_time: '*/5 * * * *' },
    { time: '10 minutes', value: 'Every 10 min', cron_time: '*/10 * * * *' },
    { time: '15 minutes', value: 'Every 15 min', cron_time: '*/15 * * * *' },
    { time: '20 minutes', value: 'Every 20 min', cron_time: '*/20 * * * *' },
    { time: '30 minutes', value: 'Every 30 min', cron_time: '*/30 * * * *' },
    { time: '1 hours', value: 'Every 1 hours', cron_time: '*/60 * * * *' },
    { time: '4 hours', value: 'Every 4 hours', cron_time: '0 */4 * * *' },
    { time: '8 hours', value: 'Every 8 hours', cron_time: '0 */8 * * *' },
    { time: '12 hours', value: 'Every 12 hours', cron_time: '0 */12 * * *' },
    { time: '24 hours', value: 'Every 24 hours', cron_time: '0 */24 * * *' },
  ],
  LTS_ACTIVE: [
    { value: 'Yes', viewValue: 'Yes' },
    { value: 'No', viewValue: 'No' },
  ],
  TIMEROPTIONS: [
    { name: '1 min', key: '1' },
    { name: '2 min', key: '2' },
    { name: '3 min', key: '3' },
    { name: '4 min', key: '4' },
    { name: '5 min', key: '5' },
    { name: '6 min', key: '6' },
    { name: '7 min', key: '7' },
    { name: '8 min', key: '8' },
    { name: '9 min', key: '9' },
    { name: '10 min', key: '10' },
    { name: '11 min', key: '11' },
    { name: '12 min', key: '12' },
    { name: '13 min', key: '13' },
    { name: '14 min', key: '14' },
    { name: '15 min', key: '15' },
    { name: '16 min', key: '16' },
    { name: '17 min', key: '17' },
    { name: '18 min', key: '18' },
    { name: '19 min', key: '19' },
    { name: '20 min', key: '20' },
    { name: '21 min', key: '21' },
    { name: '22 min', key: '22' },
    { name: '23 min', key: '23' },
    { name: '24 min', key: '24' },
    { name: '25 min', key: '25' },
    { name: '26 min', key: '26' },
    { name: '27 min', key: '27' },
    { name: '28 min', key: '28' },
    { name: '29 min', key: '29' },
    { name: '30 min', key: '30' },
    { name: '31 min', key: '31' },
    { name: '32 min', key: '32' },
    { name: '33 min', key: '33' },
    { name: '34 min', key: '34' },
    { name: '35 min', key: '35' },
    { name: '36 min', key: '36' },
    { name: '37 min', key: '37' },
    { name: '38 min', key: '38' },
    { name: '39 min', key: '39' },
    { name: '40 min', key: '40' },
    { name: '41 min', key: '41' },
    { name: '42 min', key: '42' },
    { name: '43 min', key: '43' },
    { name: '44 min', key: '44' },
    { name: '45 min', key: '45' },
    { name: '46 min', key: '46' },
    { name: '47 min', key: '47' },
    { name: '48 min', key: '48' },
    { name: '49 min', key: '49' },
    { name: '50 min', key: '50' },
    { name: '51 min', key: '51' },
    { name: '52 min', key: '52' },
    { name: '53 min', key: '53' },
    { name: '54 min', key: '54' },
    { name: '55 min', key: '55' },
    { name: '56 min', key: '56' },
    { name: '57 min', key: '57' },
    { name: '58 min', key: '58' },
    { name: '59 min', key: '59' },
  ],
  OTPOPTIONS: [
    { name: 'Yes', key: 'Yes', tmp_language: 'COMMON.ACTIONS.YES' },
    { name: 'No', key: 'No', tmp_language: 'COMMON.ACTIONS.NO' },
  ],
};
