export const configData = {
  API_URL: 'https://dbtest.rovuk.us:4207/',
  DEFAULT_LOADER_GIF: '../assets/images/rovuk-gif.gif',
  INVOICES_STATUS: [
    { name: 'Pending', key: 'Pending' },
    { name: 'Approved', key: 'Approved' },
    { name: 'Rejected', key: 'Rejected' },
    { name: 'Late', key: 'Late' },
    { name: 'Paid', key: 'Paid' },
    { name: 'Unpaid', key: 'Unpaid' },
    { name: 'Overdue', key: 'Overdue' },
  ],
  SITELANGUAGES: ['es', 'en'],
  INITIALLANGUAGE: 'en',
  LANGUAGE_ARRAY: [
    { name: 'English', value: 'en' },
    { name: 'Español', value: 'es' },
  ],
  PRIME_VENDOR_TYPE: 'Prime',
  gender: [{ value: "Male", tmp_lanaguage: "COMMON.GENDER_ALL.Male_All" },
  { value: "Female", tmp_lanaguage: "COMMON.GENDER_ALL.Female_All" }],
  Status: [
    { value: 1, viewValue: "Active", tmp_lanaguage: "COMMON.STATUS.ACTIVE" },
    { value: 2, viewValue: "Inactive", tmp_lanaguage: "COMMON.STATUS.INACTIVE" }],
  MAILBOX_MONITOR_TIME: [
    { time: '5 minutes', value: 'Every 5 min', cron_time: '*/5 * * * *' },
    { time: '10 minutes', value: 'Every 10 min', cron_time: '*/10 * * * *' },
    { time: '15 minutes', value: 'Every 15 min', cron_time: '*/15 * * * *' },
    { time: '20 minutes', value: 'Every 20 min', cron_time: '*/20 * * * *' },
    { time: '30 minutes', value: 'Every 30 min', cron_time: '*/30 * * * *' },
    { time: '1 hours', value: 'Every 1 hours', cron_time: '*/60 * * * *' },
    { time: '4 hours', value: 'Every 4 hours', cron_time: '0 */4 * * *' },
    { time: '8 hours', value: 'Every 8 hours', cron_time: '0 */8 * * *' },
    { time: '12 hours', value: 'Every 12 hours', cron_time: '0 */12 * * *' },
    { time: '24 hours', value: 'Every 24 hours', cron_time: '0 */24 * * *' },
  ],
  LTS_ACTIVE: [
    { value: 'Yes', viewValue: 'Yes' },
    { value: 'No', viewValue: 'No' },
  ],
};
